//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.TheAviator {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TheAviatorLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TheAviatorLocalization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.TheAviator.TheAviatorLocalization", typeof(TheAviatorLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Grab the blue pills benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionOne {
            get {
                return ResourceManager.GetString("DescriptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   avoid the red ones benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionTwo {
            get {
                return ResourceManager.GetString("DescriptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   distance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DistanceValue {
            get {
                return ResourceManager.GetString("DistanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   energy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fly it to the end benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   the benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameOne {
            get {
                return ResourceManager.GetString("GameOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aviator benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameTwo {
            get {
                return ResourceManager.GetString("GameTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   level benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LevelValue {
            get {
                return ResourceManager.GetString("LevelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to Replay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReplayDesktop {
            get {
                return ResourceManager.GetString("ReplayDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch to Replay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReplayMobile {
            get {
                return ResourceManager.GetString("ReplayMobile", resourceCulture);
            }
        }
    }
}
