//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.MagicSquare {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MagicSquareLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MagicSquareLocalization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.MagicSquare.MagicSquareLocalization", typeof(MagicSquareLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   × benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Congratulations! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///     benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key0 {
            get {
                return ResourceManager.GetString("Key0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key1 {
            get {
                return ResourceManager.GetString("Key1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key2 {
            get {
                return ResourceManager.GetString("Key2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key3 {
            get {
                return ResourceManager.GetString("Key3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key4 {
            get {
                return ResourceManager.GetString("Key4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key5 {
            get {
                return ResourceManager.GetString("Key5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key6 {
            get {
                return ResourceManager.GetString("Key6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key7 {
            get {
                return ResourceManager.GetString("Key7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key8 {
            get {
                return ResourceManager.GetString("Key8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   9 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Key9 {
            get {
                return ResourceManager.GetString("Key9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play again? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
    }
}
