//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.TheCube {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TheCubeLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TheCubeLocalization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.TheCube.TheCubeLocalization", typeof(TheCubeLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Average of 12: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Average12 {
            get {
                return ResourceManager.GetString("Average12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average of 25: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Average25 {
            get {
                return ResourceManager.GetString("Average25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average of 5: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Average5 {
            get {
                return ResourceManager.GetString("Average5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Best Time! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BestTime {
            get {
                return ResourceManager.GetString("BestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Angle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CameraAngle {
            get {
                return ResourceManager.GetString("CameraAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ortographic,Perspective benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CameraAngleValue {
            get {
                return ResourceManager.GetString("CameraAngleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Scheme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cube,Erno,Dust,Camo,Rain benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ColorSchemeValue {
            get {
                return ResourceManager.GetString("ColorSchemeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cube Size benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CubeSize {
            get {
                return ResourceManager.GetString("CubeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2,3,4,5 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CubeSizeValue {
            get {
                return ResourceManager.GetString("CubeSizeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FlipType {
            get {
                return ResourceManager.GetString("FlipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swift&amp;nbsp;,Smooth,Bounce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FlipTypeValue {
            get {
                return ResourceManager.GetString("FlipTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   THE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameOne {
            get {
                return ResourceManager.GetString("GameOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CUBE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameTwo {
            get {
                return ResourceManager.GetString("GameTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hue benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightness benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lightness {
            get {
                return ResourceManager.GetString("Lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cube benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saturation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scramble Length benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScrambleLength {
            get {
                return ResourceManager.GetString("ScrambleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20,25,30 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScrambleLengthValue {
            get {
                return ResourceManager.GetString("ScrambleLengthValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double click to start benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StartDesktop {
            get {
                return ResourceManager.GetString("StartDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double touch to start benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StartMobile {
            get {
                return ResourceManager.GetString("StartMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Best time: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TheBestTime {
            get {
                return ResourceManager.GetString("TheBestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0:00 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total solves: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TotalSolves {
            get {
                return ResourceManager.GetString("TotalSolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Worst time: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WorstTime {
            get {
                return ResourceManager.GetString("WorstTime", resourceCulture);
            }
        }
    }
}
