//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.Classic2048 {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Classic2048Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Classic2048Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.Classic2048.Classic2048Localization", typeof(Classic2048Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Although coded entirely from scratch, this game is a (lackluster) copy of Gabriele Cirulli&apos;s 2048, https://soferity.dev. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classic 2048 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tiles with matching number values can be merged into a single tile, which receives the values&apos; sum. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HowDescriptionOne {
            get {
                return ResourceManager.GetString("HowDescriptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To win, get a 2048 tile. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HowDescriptionThree {
            get {
                return ResourceManager.GetString("HowDescriptionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///    To move the board, use the directional arrows - or swipe. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HowDescriptionTwo {
            get {
                return ResourceManager.GetString("HowDescriptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    How do I play?  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HowDoPlay {
            get {
                return ResourceManager.GetString("HowDoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    New Game  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Score  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///    What is this?  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WhatIsThis {
            get {
                return ResourceManager.GetString("WhatIsThis", resourceCulture);
            }
        }
    }
}
