//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.Coloron {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColoronLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColoronLocalization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.Coloron.ColoronLocalization", typeof(ColoronLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Always match the benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlwaysMatch {
            get {
                return ResourceManager.GetString("AlwaysMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Red, Yellow, Purple). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Ball {
            get {
                return ResourceManager.GetString("Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ball and bar colors. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BallBar {
            get {
                return ResourceManager.GetString("BallBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bouncing ball benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BouncingBall {
            get {
                return ResourceManager.GetString("BouncingBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   changes color. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ChangesColor {
            get {
                return ResourceManager.GetString("ChangesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coloron benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on the bar to switch the colors benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GuideDesktop {
            get {
                return ResourceManager.GetString("GuideDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap on the bar to switch the colors benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GuideMobile {
            get {
                return ResourceManager.GetString("GuideMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hint benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   color always comes first. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HintDescription {
            get {
                return ResourceManager.GetString("HintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on the bars to change the color! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LearnDesktop {
            get {
                return ResourceManager.GetString("LearnDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap on the bars to change the color! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LearnMobile {
            get {
                return ResourceManager.GetString("LearnMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soferity: Game Portal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Again benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coloron benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Tweet {
            get {
                return ResourceManager.GetString("Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet to challenge friends benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TweetChallenge {
            get {
                return ResourceManager.GetString("TweetChallenge", resourceCulture);
            }
        }
    }
}
