//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.Lazy2048 {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lazy2048Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lazy2048Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.Lazy2048.Lazy2048Localization", typeof(Lazy2048Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Lazy 2048 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to play: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HowToPlay {
            get {
                return ResourceManager.GetString("HowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s party! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LetsParty {
            get {
                return ResourceManager.GetString("LetsParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW GAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLAY AGAIN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⭐️ Or Sit simply benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayDescriptionFourPartOne {
            get {
                return ResourceManager.GetString("PlayDescriptionFourPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///    (recommended for highly lazy ones) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayDescriptionFourPartTwo {
            get {
                return ResourceManager.GetString("PlayDescriptionFourPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⭐️ Drag pieces around benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayDescriptionOne {
            get {
                return ResourceManager.GetString("PlayDescriptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⭐️ Get to 2048 to win the game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayDescriptionThree {
            get {
                return ResourceManager.GetString("PlayDescriptionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⭐️ Stack those with the same number benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayDescriptionTwo {
            get {
                return ResourceManager.GetString("PlayDescriptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High Quality benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound FX benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You win benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success is commemorated; failure merely remembered. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WinDescriptionOne {
            get {
                return ResourceManager.GetString("WinDescriptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t be afraid to try again. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WinDescriptionTwo {
            get {
                return ResourceManager.GetString("WinDescriptionTwo", resourceCulture);
            }
        }
    }
}
