//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.SweetMemory {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SweetMemoryLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SweetMemoryLocalization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.SweetMemory.SweetMemoryLocalization", typeof(SweetMemoryLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExitCancel {
            get {
                return ResourceManager.GetString("ExitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes, Close Game! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your progress will be Lost! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Moves benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MovesText {
            get {
                return ResourceManager.GetString("MovesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RestartCancel {
            get {
                return ResourceManager.GetString("RestartCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes, Restart Game! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RestartConfirm {
            get {
                return ResourceManager.GetString("RestartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your progress will be lost! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RestartText {
            get {
                return ResourceManager.GetString("RestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RestartTitle {
            get {
                return ResourceManager.GetString("RestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Again! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WinConfirm {
            get {
                return ResourceManager.GetString("WinConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   With {0} Moves and {1} Stars.{2}Congratulations! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WinText {
            get {
                return ResourceManager.GetString("WinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Congratulations! You Won! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WinTitle {
            get {
                return ResourceManager.GetString("WinTitle", resourceCulture);
            }
        }
    }
}
