//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Main {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLocalization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Main.MainLocalization", typeof(MainLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Classic 2048 is a 2D action platformer with a focus on exploration and combat. You play as a cat who has been separated from their owner and must find their way home. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionClassic2048 {
            get {
                return ResourceManager.GetString("DescriptionClassic2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hextris is a 2D action platformer with a focus on exploration and combat. You play as a cat who has been separated from their owner and must find their way home. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionHextris {
            get {
                return ResourceManager.GetString("DescriptionHextris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lazy 2048 is a 2D action platformer with a focus on exploration and combat. You play as a cat who has been separated from their owner and must find their way home. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionLazy2048 {
            get {
                return ResourceManager.GetString("DescriptionLazy2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic Square is a 2D action platformer with a focus on exploration and combat. You play as a cat who has been separated from their owner and must find their way home. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionMagicSquare {
            get {
                return ResourceManager.GetString("DescriptionMagicSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sweet Memory is a memory game. Flip the squares and see the icon behind them. Then look behind more squares to find the same icon. If you find the same icon, you get a point. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionSweetMemory {
            get {
                return ResourceManager.GetString("DescriptionSweetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Aviator is a action platform game. Collect batteries by plane and escape from the meteorites. Level up as the distance traveled increases. Don&apos;t forget to control your speed while flying. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionTheAviator {
            get {
                return ResourceManager.GetString("DescriptionTheAviator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Cube is a rubik&apos;s cube completion game. With the various settings offered, you can make your own custom rubik&apos;s cube. So you can test yourself. If you give up, you lose. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionTheCube {
            get {
                return ResourceManager.GetString("DescriptionTheCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tic Tac Toe is a 2D action platformer with a focus on exploration and combat. You play as a cat who has been separated from their owner and must find their way home. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionTicTacToe {
            get {
                return ResourceManager.GetString("DescriptionTicTacToe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tower Block is a game of stacking blocks. As you stack blocks on top of each other, you earn points. The higher you stack, the more points you earn. The game ends when you can no longer stack blocks. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionTowerBlock {
            get {
                return ResourceManager.GetString("DescriptionTowerBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tower of Hanoi is a puzzle game. The puzzle begins with the disks stacked on one rod in order of decreasing size, the smallest at the top, thus approximating a conical shape. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionTowerOfHanoi {
            get {
                return ResourceManager.GetString("DescriptionTowerOfHanoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valorous Rabbit is an action adventure game. Try to escape from the hedgehog by taking the carrots. The most important thing is to never get caught by a hedgehog. If you get caught in the hedgehog, it&apos;s game over. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionValorousRabbit {
            get {
                return ResourceManager.GetString("DescriptionValorousRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/classic2048.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageClassic2048 {
            get {
                return ResourceManager.GetString("ImageClassic2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/hextris.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageHextris {
            get {
                return ResourceManager.GetString("ImageHextris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/lazy2048.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageLazy2048 {
            get {
                return ResourceManager.GetString("ImageLazy2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/magicsquare.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageMagicSquare {
            get {
                return ResourceManager.GetString("ImageMagicSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/sweetmemory.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageSweetMemory {
            get {
                return ResourceManager.GetString("ImageSweetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/theaviator.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageTheAviator {
            get {
                return ResourceManager.GetString("ImageTheAviator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/thecube.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageTheCube {
            get {
                return ResourceManager.GetString("ImageTheCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/tictactoe.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageTicTacToe {
            get {
                return ResourceManager.GetString("ImageTicTacToe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/towerblock.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageTowerBlock {
            get {
                return ResourceManager.GetString("ImageTowerBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/towerofhanoi.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageTowerOfHanoi {
            get {
                return ResourceManager.GetString("ImageTowerOfHanoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   img/game/valorousrabbit.jpg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageValorousRabbit {
            get {
                return ResourceManager.GetString("ImageValorousRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To give points, you must play first. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayFirst {
            get {
                return ResourceManager.GetString("PlayFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayGame {
            get {
                return ResourceManager.GetString("PlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trend benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StateHit {
            get {
                return ResourceManager.GetString("StateHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StateNew {
            get {
                return ResourceManager.GetString("StateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StateOld {
            get {
                return ResourceManager.GetString("StateOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classic 2048 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleClassic2048 {
            get {
                return ResourceManager.GetString("TitleClassic2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hextris benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleHextris {
            get {
                return ResourceManager.GetString("TitleHextris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lazy 2048 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleLazy2048 {
            get {
                return ResourceManager.GetString("TitleLazy2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic Square benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleMagicSquare {
            get {
                return ResourceManager.GetString("TitleMagicSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sweet Memory benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleSweetMemory {
            get {
                return ResourceManager.GetString("TitleSweetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Aviator benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleTheAviator {
            get {
                return ResourceManager.GetString("TitleTheAviator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Cube benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleTheCube {
            get {
                return ResourceManager.GetString("TitleTheCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tic Tac Toe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleTicTacToe {
            get {
                return ResourceManager.GetString("TitleTicTacToe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tower Block benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleTowerBlock {
            get {
                return ResourceManager.GetString("TitleTowerBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tower of Hanoi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleTowerOfHanoi {
            get {
                return ResourceManager.GetString("TitleTowerOfHanoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valorous Rabbit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TitleValorousRabbit {
            get {
                return ResourceManager.GetString("TitleValorousRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeAction {
            get {
                return ResourceManager.GetString("TypeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adventure benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeAdventure {
            get {
                return ResourceManager.GetString("TypeAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Education benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeEducation {
            get {
                return ResourceManager.GetString("TypeEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fighting benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeFighting {
            get {
                return ResourceManager.GetString("TypeFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FPS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeFPS {
            get {
                return ResourceManager.GetString("TypeFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lucky benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeLucky {
            get {
                return ResourceManager.GetString("TypeLucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MMO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeMMO {
            get {
                return ResourceManager.GetString("TypeMMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOBA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeMOBA {
            get {
                return ResourceManager.GetString("TypeMOBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiplayer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeMultiplayer {
            get {
                return ResourceManager.GetString("TypeMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeMusic {
            get {
                return ResourceManager.GetString("TypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Platform benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypePlatform {
            get {
                return ResourceManager.GetString("TypePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puzzle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypePuzzle {
            get {
                return ResourceManager.GetString("TypePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Racing benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeRacing {
            get {
                return ResourceManager.GetString("TypeRacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RPG benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeRPG {
            get {
                return ResourceManager.GetString("TypeRPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RTS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeRTS {
            get {
                return ResourceManager.GetString("TypeRTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shooter benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeShooter {
            get {
                return ResourceManager.GetString("TypeShooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeSimulation {
            get {
                return ResourceManager.GetString("TypeSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Singleplayer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeSingleplayer {
            get {
                return ResourceManager.GetString("TypeSingleplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sports benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeSports {
            get {
                return ResourceManager.GetString("TypeSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strategy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeStrategy {
            get {
                return ResourceManager.GetString("TypeStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TPS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TypeTPS {
            get {
                return ResourceManager.GetString("TypeTPS", resourceCulture);
            }
        }
    }
}
