//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal.Resources.Languages.Game.TowerBlock {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TowerBlockLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TowerBlockLocalization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamePortal.Resources.Languages.Game.TowerBlock.TowerBlockLocalization", typeof(TowerBlockLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Click (or press the spacebar) to place the block benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionDesktop {
            get {
                return ResourceManager.GetString("DescriptionDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch to place the block benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionMobile {
            get {
                return ResourceManager.GetString("DescriptionMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Over benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click or spacebar to start again benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameOverDesktop {
            get {
                return ResourceManager.GetString("GameOverDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch to start again benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameOverMobile {
            get {
                return ResourceManager.GetString("GameOverMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You did great, you&apos;re the best. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GameOverOne {
            get {
                return ResourceManager.GetString("GameOverOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
